/**
 * affiliate_core.test.js: the pure rules of the affiliate module
 * (netlify/functions/_affiliate_core.js). Money, attribution policy, the
 * commission state machine, redirect URL building, code validation, CSV.
 * Run: `node tests/affiliate_core.test.js` from brandgeo-dashboard/.
 */
const assert = require('assert')
const path = require('path')
const core = require(path.join(__dirname, '..', 'netlify', 'functions', '_affiliate_core.js'))

let passed = 0
const ok = (n) => { passed++; console.log('  ok -', n) }
const section = (n) => console.log(`\n${n}`)

section('money: integers only, no floats')
assert.strictEqual(core.majorToCents('12.50'), 1250)
assert.strictEqual(core.majorToCents('299'), 29900)
assert.strictEqual(core.majorToCents('0.1'), 10)
assert.strictEqual(core.majorToCents('1,5'), 150)
assert.strictEqual(core.majorToCents('12.505'), null)
assert.strictEqual(core.majorToCents('abc'), null)
assert.strictEqual(core.centsToMajor(5980), '59.80')
assert.strictEqual(core.centsToMajor(5), '0.05')
assert.strictEqual(core.parseCents(29900), 29900)
assert.strictEqual(core.parseCents('29900'), 29900)
assert.strictEqual(core.parseCents(1.5), null)
assert.strictEqual(core.parseCents(-1), null)
ok('majorToCents / centsToMajor / parseCents round-trip without floating point')
assert.strictEqual(core.percentOf(29900, 2000), 5980)
assert.strictEqual(core.percentOf(1, 5000), 1, 'half a cent rounds up')
assert.strictEqual(core.percentOf(3, 3333), 1)
assert.strictEqual(core.percentOf(29900, 0), 0)
assert.throws(() => core.percentOf(1.5, 100))
ok('percentOf uses integer basis points and rounds half up')

section('commission rules')
const program = { currency: 'EUR', lead_commission_cents: 0, sale_commission_type: 'percent', sale_commission_cents: 0, sale_commission_bps: 2000, recurring_commission_bps: 2000, recurring_months: 12, attribution_days: 30, approval_days: 30, attribution_mode: 'last_touch' }
let rules = core.effectiveRules(program, null)
let r = core.computeCommission({ rules, conversionType: 'sale', amountCents: 29900, occurredAt: '2026-09-12T00:00:00Z' })
assert.strictEqual(r.amountCents, 5980)
assert.strictEqual(r.snapshot.rule, 'percent_of_sale')
ok('20% of EUR 299.00 is EUR 59.80')
r = core.computeCommission({ rules, conversionType: 'lead', amountCents: 0, occurredAt: '2026-09-12T00:00:00Z' })
assert.strictEqual(r.amountCents, 0)
assert.strictEqual(r.reason, 'lead_not_commissionable')
ok('a raw lead earns nothing')
const leadProgram = { ...program, lead_commission_cents: 10000, sale_commission_type: 'fixed', sale_commission_cents: 50000, recurring_commission_bps: 0 }
rules = core.effectiveRules(leadProgram, null)
r = core.computeCommission({ rules, conversionType: 'qualified_lead', amountCents: 0, occurredAt: '2026-09-12T00:00:00Z' })
assert.strictEqual(r.amountCents, 10000)
r = core.computeCommission({ rules, conversionType: 'sale', amountCents: 123456, occurredAt: '2026-09-12T00:00:00Z' })
assert.strictEqual(r.amountCents, 50000)
assert.strictEqual(r.snapshot.rule, 'fixed_per_sale')
r = core.computeCommission({ rules, conversionType: 'recurring', amountCents: 29900, occurredAt: '2026-09-12T00:00:00Z' })
assert.strictEqual(r.amountCents, 0)
assert.strictEqual(r.reason, 'one_time_commission_only')
ok('fixed per qualified lead, fixed per sale, and no recurring when the program is one-time')

rules = core.effectiveRules(program, { custom_rules: { sale_commission_bps: 2500 } })
r = core.computeCommission({ rules, conversionType: 'sale', amountCents: 29900, occurredAt: '2026-09-12T00:00:00Z' })
assert.strictEqual(r.amountCents, 7475)
assert.strictEqual(r.snapshot.custom, true)
assert.strictEqual(rules.recurring_commission_bps, 2000, 'keys not overridden keep the program value')
ok('a custom per-affiliate rate overrides only the keys it sets')

rules = core.effectiveRules(program, null)
const firstSale = '2026-01-15T10:00:00Z'
const until = core.recurringUntil(rules, firstSale)
assert.strictEqual(until.toISOString(), '2027-01-15T10:00:00.000Z')
r = core.computeCommission({ rules, conversionType: 'recurring', amountCents: 29900, occurredAt: '2026-12-15T10:00:00Z', attribution: { recurring_until: until.toISOString() } })
assert.strictEqual(r.amountCents, 5980)
r = core.computeCommission({ rules, conversionType: 'recurring', amountCents: 29900, occurredAt: '2027-02-15T10:00:00Z', attribution: { recurring_until: until.toISOString() } })
assert.strictEqual(r.amountCents, 0)
assert.strictEqual(r.reason, 'recurring_window_ended')
r = core.computeCommission({ rules, conversionType: 'recurring', amountCents: 29900, occurredAt: '2026-12-15T10:00:00Z', attribution: { recurring_until: until.toISOString(), subscription_ended_at: '2026-11-01T00:00:00Z' } })
assert.strictEqual(r.reason, 'subscription_ended')
assert.strictEqual(core.recurringUntil({ ...rules, recurring_months: null }, firstSale), null, 'null months = unlimited')
ok('recurring pays inside the 12-month window from the first sale and stops after it or after cancellation')

assert.strictEqual(core.approveAfter('2026-09-12T00:00:00Z', 30).toISOString(), '2026-10-12T00:00:00.000Z')
ok('approval delay defaults to 30 days after the sale')
assert.strictEqual(core.summarizeRules(program), '20% of every payment for the first 12 months')
assert.strictEqual(core.summarizeRules(leadProgram), 'EUR 500.00 per sale, plus EUR 100.00 per qualified lead')
ok('summarizeRules produces the plain-English line the public page shows')

section('attribution policy')
let d = core.decideAttribution({ existing: null, incoming: { membership_id: 'm1', source: 'link', at: '2026-09-01T00:00:00Z' }, mode: 'last_touch' })
assert.strictEqual(d.winner, 'incoming')
const existing = { membership_id: 'm1', source: 'link', last_touch_at: '2026-09-01T00:00:00Z', expires_at: '2026-10-01T00:00:00Z', converted_at: null }
d = core.decideAttribution({ existing, incoming: { membership_id: 'm2', source: 'link', at: '2026-09-10T00:00:00Z' }, mode: 'last_touch', now: '2026-09-10T00:00:00Z' })
assert.strictEqual(d.winner, 'incoming')
assert.deepStrictEqual(d.flags, ['duplicate_customer'])
ok('last touch: the newest link wins and the switch is flagged')
d = core.decideAttribution({ existing, incoming: { membership_id: 'm2', source: 'link', at: '2026-09-10T00:00:00Z' }, mode: 'first_touch', now: '2026-09-10T00:00:00Z' })
assert.strictEqual(d.winner, 'existing')
d = core.decideAttribution({ existing, incoming: { membership_id: 'm2', source: 'link', at: '2026-11-10T00:00:00Z' }, mode: 'first_touch', now: '2026-11-10T00:00:00Z' })
assert.strictEqual(d.winner, 'incoming', 'an expired first touch no longer holds the customer')
ok('first touch: the first link keeps the customer until its window expires')
d = core.decideAttribution({ existing, incoming: { membership_id: 'm2', source: 'coupon', at: '2026-09-10T00:00:00Z' }, mode: 'first_touch', now: '2026-09-10T00:00:00Z' })
assert.strictEqual(d.winner, 'incoming')
d = core.decideAttribution({ existing: { ...existing, source: 'coupon' }, incoming: { membership_id: 'm2', source: 'link', at: '2026-09-10T00:00:00Z' }, mode: 'last_touch' })
assert.strictEqual(d.winner, 'existing')
ok('a coupon code overrides a link in both modes')
d = core.decideAttribution({ existing: { ...existing, source: 'manual' }, incoming: { membership_id: 'm2', source: 'coupon', at: '2026-09-10T00:00:00Z' }, mode: 'last_touch' })
assert.strictEqual(d.winner, 'existing')
d = core.decideAttribution({ existing: { ...existing, source: 'coupon' }, incoming: { membership_id: 'm2', source: 'manual', at: '2026-09-10T00:00:00Z' }, mode: 'last_touch' })
assert.strictEqual(d.winner, 'incoming')
ok('a manual attribution beats everything, in both directions')
d = core.decideAttribution({ existing: { ...existing, converted_at: '2026-09-05T00:00:00Z' }, incoming: { membership_id: 'm2', source: 'coupon', at: '2026-09-10T00:00:00Z' }, mode: 'last_touch' })
assert.strictEqual(d.winner, 'existing')
ok('a customer who already bought stays with the affiliate who brought the first sale')

section('self-referral detection')
const aff = { email: 'partner@agency-example.com', website: 'https://agency-example.com', email_hash: core.hashEmail('partner@agency-example.com') }
assert.strictEqual(core.isSelfReferral({ affiliate: aff, customerEmail: 'partner@agency-example.com' }), true)
assert.strictEqual(core.isSelfReferral({ affiliate: aff, customerEmail: 'boss@agency-example.com' }), true, 'same private domain')
assert.strictEqual(core.isSelfReferral({ affiliate: aff, customerEmail: 'ceo@shop.agency-example.com' }), true, 'subdomain of the affiliate website')
assert.strictEqual(core.isSelfReferral({ affiliate: aff, customerEmail: 'someone@example.org' }), false)
assert.strictEqual(core.isSelfReferral({ affiliate: { ...aff, email: 'p@gmail.com', website: null }, customerEmail: 'q@gmail.com' }), false, 'public mail domains do not count')
assert.strictEqual(core.isSelfReferral({ affiliate: aff, customerEmailHash: aff.email_hash }), true, 'hash-only match')
ok('self-referrals are flagged by email, private domain, website domain, or hash')

section('commission state machine')
assert.strictEqual(core.canTransition('pending', 'approved'), true)
assert.strictEqual(core.canTransition('pending', 'paid'), false)
assert.strictEqual(core.canTransition('approved', 'payable'), true)
assert.strictEqual(core.canTransition('payable', 'paid'), true)
assert.strictEqual(core.canTransition('payable', 'approved'), true, 'a cancelled batch returns to approved')
assert.strictEqual(core.canTransition('paid', 'reversed'), false, 'paid is final; refunds flag reconciliation instead')
assert.strictEqual(core.canTransition('reversed', 'pending'), false)
assert.strictEqual(core.canTransition('rejected', 'pending'), true)
ok('only the documented transitions are allowed')

section('redirect URL')
let u = new URL(core.buildRedirectUrl({ destination: 'https://getbrandgeo.com/', code: 'DANIEL10', visitToken: 'abc123def456', programSlug: 'brandgeo', attributionDays: 30, incomingQuery: {} }))
assert.strictEqual(u.searchParams.get('ref'), 'DANIEL10')
assert.strictEqual(u.searchParams.get('bg_rid'), 'abc123def456')
assert.strictEqual(u.searchParams.get('ref_days'), '30')
assert.strictEqual(u.searchParams.get('utm_source'), 'affiliate')
assert.strictEqual(u.searchParams.get('utm_medium'), 'referral')
assert.strictEqual(u.searchParams.get('utm_campaign'), 'brandgeo')
ok('ref, bg_rid, ref_days and the three UTMs are added')
u = new URL(core.buildRedirectUrl({ destination: 'https://getbrandgeo.com/pricing?plan=growth', code: 'X1', visitToken: 't', programSlug: 'brandgeo', attributionDays: 30, incomingQuery: { utm_campaign: 'newsletter-sept', utm_content: 'hero', ref: 'INJECTED' } }))
assert.strictEqual(u.searchParams.get('plan'), 'growth', 'destination query preserved')
assert.strictEqual(u.searchParams.get('utm_campaign'), 'newsletter-sept', 'partner UTM wins')
assert.strictEqual(u.searchParams.get('utm_content'), 'hero', 'other params pass through')
assert.strictEqual(u.searchParams.get('ref'), 'X1', 'an injected ref on the click cannot override the real code')
ok('existing UTMs are preserved and the affiliate cannot forge ref via the click query')
assert.strictEqual(core.isSafeDestination('https://example.com/x'), true)
assert.strictEqual(core.isSafeDestination('javascript:alert(1)'), false)
assert.strictEqual(core.isSafeDestination('not a url'), false)
ok('only http(s) destinations are accepted')

section('codes, slugs, keys')
assert.strictEqual(core.isValidCode('DANIEL10'), true)
assert.strictEqual(core.isValidCode('ab'), false, 'too short')
assert.strictEqual(core.isValidCode('-BAD'), false, 'cannot start with a hyphen')
assert.strictEqual(core.isValidCode('has space'), false)
assert.strictEqual(core.normalizeCode(' daniel10 '), 'DANIEL10')
assert.strictEqual(core.isValidSlug('brandgeo'), true)
assert.strictEqual(core.isValidSlug('Brand GEO'), false)
const suggested = core.suggestCode('Ana Maria Popescu')
assert.ok(core.isValidCode(suggested), suggested)
assert.ok(/^ANA/.test(suggested))
const key = core.makeApiKey('brandgeo')
assert.ok(/^bgaff_brandgeo_[a-f0-9]{48}$/.test(key))
assert.strictEqual(core.hashApiKey(key).length, 64)
assert.notStrictEqual(core.hashApiKey(key), key)
assert.strictEqual(core.apiKeyPrefix(key).length < key.length, true)
ok('code format, slug format, suggested codes and API keys behave')
assert.strictEqual(core.maskEmail('julia@example.com'), 'j***@example.com')
assert.strictEqual(core.hashEmail(' Julia@Example.com '), core.hashEmail('julia@example.com'))
ok('emails are masked for display and hashed case-insensitively')

section('conversion input validation')
let v = core.validateConversionInput({ idempotency_key: 'order_1', conversion_type: 'sale', amount: '299.00', currency: 'eur', customer_email: 'A@B.com', metadata: { a: 1 } })
assert.deepStrictEqual(v.errors, [])
assert.strictEqual(v.row.amount_cents, 29900)
assert.strictEqual(v.row.currency, 'EUR')
assert.strictEqual(v.row.customer_email, 'a@b.com')
assert.strictEqual(v.row.status, 'confirmed')
v = core.validateConversionInput({ idempotency_key: 'order_2', conversion_type: 'sale', amount_cents: 12.5 })
assert.ok(v.errors.some((e) => /amount_cents/.test(e)))
v = core.validateConversionInput({ conversion_type: 'nope' })
assert.ok(v.errors.some((e) => /idempotency_key/.test(e)))
assert.ok(v.errors.some((e) => /conversion_type/.test(e)))
v = core.validateConversionInput({ idempotency_key: 'k', conversion_type: 'sale', commission: '999.00' })
assert.strictEqual(v.row.commission, undefined, 'a commission sent by the client is ignored')
const big = { blob: 'x'.repeat(5000) }
v = core.validateConversionInput({ idempotency_key: 'k', conversion_type: 'sale', metadata: big })
assert.deepStrictEqual(v.row.metadata, { truncated: true })
ok('validateConversionInput accepts major or cents, normalises, ignores client commissions, caps metadata')

section('program input validation')
v = core.validateProgramInput({ slug: 'Bad Slug', name: '', destination_url: 'ftp://x' })
assert.strictEqual(v.errors.length, 3)
v = core.validateProgramInput({ slug: 'brandgeo', name: 'BrandGEO', destination_url: 'https://getbrandgeo.com/', sale_commission_bps: 2000, recurring_months: '' })
assert.deepStrictEqual(v.errors, [])
assert.strictEqual(v.row.recurring_months, null)
v = core.validateProgramInput({ sale_commission_bps: 20000 }, { partial: true })
assert.ok(v.errors[0].includes('sale_commission_bps'))
ok('program validation rejects bad slugs, urls and out-of-range rates; partial patches skip required fields')
v = core.validateCustomRules({ sale_commission_bps: 2500, bogus: 1 })
assert.deepStrictEqual(v.errors, [])
assert.deepStrictEqual(v.rules, { sale_commission_bps: 2500 })
ok('custom rules keep only known keys')

section('payout details')
const details = core.sanitizePayoutDetails('wise', { account_holder: 'A', email: 'a@b.com', password: 'nope', card_number: '4111', iban: 'ES00' })
assert.deepStrictEqual(Object.keys(details).sort(), ['account_holder', 'email', 'iban'])
ok('payout details keep only the fields a transfer needs; passwords and card numbers are dropped')

section('CSV export')
const csv = core.toCsv(['a', 'b'], [{ a: 'x,y', b: '=SUM(1)' }, { a: 'line\nbreak', b: null }])
const lines = csv.split('\r\n')
assert.strictEqual(lines[0], 'a,b')
assert.strictEqual(lines[1], '"x,y",\'=SUM(1)')
assert.strictEqual(lines[2], '"line\nbreak",')
ok('CSV quotes commas and newlines and neutralises formula injection')
assert.deepStrictEqual(core.EXPORT_COLUMNS.commissions, ['commission_id', 'conversion_id', 'program_slug', 'affiliate_id', 'affiliate_email', 'status', 'amount', 'currency', 'approve_after', 'approved_at', 'paid_at', 'payout_batch_id', 'reconciliation_flag', 'created_at'])
ok('export column names are stable')

console.log(`\n${passed} checks passed`)
