/**
 * affiliate_flow.test.js: the whole affiliate lifecycle through the real
 * Netlify handlers against the in-memory Supabase fake. This is the 14-step
 * manual scenario from the brief, automated:
 *
 *   two programs -> invitation -> public application (approve, reject) ->
 *   referral click -> lead and sale through the conversion API -> idempotency
 *   -> cross-program isolation -> coupon override -> last touch vs first touch
 *   -> refund reversal -> recurring -> approve -> payout batch -> mark paid ->
 *   refund after payout -> affiliate portal view -> CSV export -> audit ->
 *   no hard deletes of financial rows.
 *
 * Run: `node tests/affiliate_flow.test.js` from brandgeo-dashboard/.
 */
const assert = require('assert')
const env = require('./helpers/affiliate_test_env')
const { createFakeSupabase } = require('./helpers/fake_supabase_mem')

env.installAuthMock({ tokens: { 'admin-jwt': { role: 'admin', user: { id: 'admin-1', email: 'admin@example.com' } } } })
const admin = env.fn('affiliate-admin.js')
const apply = env.fn('affiliate-apply.js')
const conversions = env.fn('affiliate-conversions.js')
const portal = env.fn('affiliate-portal.js')
const redirect = env.fn('affiliate-redirect.js')
const programsPublic = env.fn('affiliate-programs-public.js')
const core = env.fn('_affiliate_core.js')

let passed = 0
const ok = (n) => { passed++; console.log('  ok -', n) }
const section = (n) => console.log(`\n${n}`)

let clock = new Date('2026-09-12T10:00:00Z')
const db = createFakeSupabase({ now: () => clock })
const call = (h, ev) => h.handle(ev, { supabase: db }).then(env.parse)
const adminPost = (body) => call(admin, env.post(body, { token: 'admin-jwt' }))
const api = (key, body) => call(conversions, env.post(body, { token: key, origin: null }))
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/128.0'
const click = (p, { ua = UA, ip = '203.0.113.5', query = {}, referer = 'https://partner-a.example.com/post', method = 'GET' } = {}) =>
  call(redirect, env.get(p, { method, query, headers: { 'user-agent': ua, 'x-forwarded-for': ip, referer } }))
const tokenFromJoinUrl = (u) => decodeURIComponent(u.split('/affiliate/join/')[1])
const rows = (t) => db.rows(t)

async function main() {
  section('1. two independent programs')
  let r = await adminPost({ action: 'programs.create', slug: 'brandgeo', name: 'BrandGEO', tagline: 'AI visibility for brands', destination_url: 'https://getbrandgeo.com/', status: 'active', is_public: true, currency: 'EUR', sale_commission_type: 'percent', sale_commission_bps: 2000, recurring_commission_bps: 2000, recurring_months: 12, attribution_days: 30, approval_days: 30, min_payout_cents: 5000 })
  assert.strictEqual(r.status, 201, JSON.stringify(r.body))
  const P1 = r.body.program
  assert.strictEqual(P1.has_api_key, false)
  assert.strictEqual(P1.commission_summary, '20% of every payment for the first 12 months')
  assert.strictEqual(P1.api_key_hash, undefined)
  r = await adminPost({ action: 'programs.create', slug: 'partner-two', name: 'Partner Two', destination_url: 'https://partner-two.example.com/', status: 'active', is_public: false, currency: 'EUR', sale_commission_type: 'fixed', sale_commission_cents: 50000, lead_commission_cents: 10000, approval_days: 0, attribution_days: 60, min_payout_cents: 10000 })
  assert.strictEqual(r.status, 201, JSON.stringify(r.body))
  const P2 = r.body.program
  r = await adminPost({ action: 'programs.create', slug: 'brandgeo', name: 'Dup', destination_url: 'https://x.example.com/' })
  assert.strictEqual(r.status, 409)
  r = await adminPost({ action: 'programs.create', slug: 'Bad Slug', name: '', destination_url: 'ftp://x' })
  assert.strictEqual(r.status, 400)
  assert.strictEqual(r.body.errors.length, 3)
  r = await adminPost({ action: 'programs.create', slug: 'draft-one', name: 'Draft', destination_url: 'https://draft.example.com/', status: 'draft', is_public: true })
  assert.strictEqual(r.status, 201)
  ok('created a public percent program, a private fixed program and a draft; duplicate slug 409; invalid input 400')

  r = await call(programsPublic, env.get('/x', { headers: { origin: 'https://getbrandgeo.com' } }))
  assert.deepStrictEqual(r.body.programs.map((p) => p.slug), ['brandgeo'])
  assert.strictEqual(r.body.programs[0].sale_commission_percent, 20)
  assert.strictEqual(r.body.programs[0].min_payout, '50.00')
  ok('the public /affiliates page sees only the active public program')

  r = await adminPost({ action: 'programs.rotate_key', id: P1.id })
  assert.strictEqual(r.status, 200)
  const KEY1 = r.body.api_key
  assert.match(KEY1, /^bgaff_brandgeo_[a-f0-9]{48}$/)
  r = await adminPost({ action: 'programs.rotate_key', id: P2.id })
  const KEY2 = r.body.api_key
  r = await adminPost({ action: 'programs.list' })
  assert.strictEqual(r.body.programs.find((p) => p.id === P1.id).has_api_key, true)
  assert.ok(!JSON.stringify(r.body).includes(KEY1.slice(-20)))
  ok('each program has its own API key, shown once and stored hashed')

  section('2. invitation to program 1')
  r = await adminPost({ action: 'affiliates.invite', email: 'Ana@Partner-A.example.com', full_name: 'Ana Partner', website: 'https://partner-a.example.com', country: 'ES', program_slugs: ['brandgeo'], code: 'ANA10' })
  assert.strictEqual(r.status, 201, JSON.stringify(r.body))
  assert.strictEqual(r.body.memberships[0].code, 'ANA10')
  assert.strictEqual(r.body.memberships[0].status, 'invited')
  assert.strictEqual(r.body.email_sent, false, 'no RESEND_API_KEY in tests')
  const anaJoin = tokenFromJoinUrl(r.body.join_url)
  const ana = rows('affiliates').find((a) => a.email === 'ana@partner-a.example.com')
  assert.strictEqual(ana.status, 'invited')
  assert.strictEqual(ana.invite_token_hash, core.sha256(anaJoin))
  ok('invited Ana with code ANA10; email lower-cased; invite token stored as a hash')

  r = await click('/r/brandgeo/ANA10')
  assert.strictEqual(r.status, 302)
  assert.strictEqual(r.headers.Location, 'https://getbrandgeo.com/')
  assert.strictEqual(rows('affiliate_visits').length, 0)
  ok('before she accepts, her link still redirects but records nothing')

  r = await call(portal, env.post({ action: 'join_preview', token: anaJoin }))
  assert.strictEqual(r.status, 200)
  assert.strictEqual(r.body.affiliate.email, 'a***@partner-a.example.com')
  assert.strictEqual(r.body.programs[0].slug, 'brandgeo')
  assert.strictEqual(r.body.programs[0].membership_status, 'invited')
  r = await call(portal, env.post({ action: 'join_accept', token: anaJoin, terms_accepted: true }))
  assert.strictEqual(r.status, 400)
  r = await call(portal, env.post({ action: 'join_accept', token: anaJoin, terms_accepted: true, privacy_accepted: true, payout_method: 'wise', payout_details: { account_holder: 'Ana Partner', email: 'ana@partner-a.example.com', iban: 'ES00 0000', password: 'never', card_number: '4111' } }))
  assert.strictEqual(r.status, 200, JSON.stringify(r.body))
  assert.match(r.body.action_link, /^https:\/\/fake\.supabase\/auth/)
  const anaRow = rows('affiliates').find((a) => a.id === ana.id)
  assert.strictEqual(anaRow.status, 'active')
  assert.ok(anaRow.user_id)
  assert.strictEqual(anaRow.terms_version, portal.AFFILIATE_TERMS_VERSION)
  assert.deepStrictEqual(Object.keys(anaRow.payout_details).sort(), ['account_holder', 'email', 'iban'])
  assert.strictEqual(anaRow.invite_token_hash, null)
  const mAna1 = rows('affiliate_memberships').find((m) => m.affiliate_id === ana.id && m.program_id === P1.id)
  assert.strictEqual(mAna1.status, 'active')
  r = await call(portal, env.post({ action: 'join_preview', token: anaJoin }))
  assert.strictEqual(r.status, 404)
  db.addUser('ana-jwt', { id: anaRow.user_id, email: anaRow.email })
  ok('Ana accepted: terms recorded, payout details sanitised, membership active, magic link issued, token single-use')

  section('3. public application to program 1')
  const application = { program: 'brandgeo', full_name: 'Ben Creator', email: 'ben@creator-b.example.com', website: 'https://creator-b.example.com', country: 'DE', promo_method: 'Weekly newsletter on AI tools', payout_method: 'paypal', terms_accepted: true, privacy_accepted: true }
  const applyPost = (body, ip = '198.51.100.7') => call(apply, env.post(body, { origin: 'https://getbrandgeo.com', headers: { 'x-forwarded-for': ip, 'user-agent': UA } }))
  r = await applyPost({ ...application, website_url: 'http://spam.example' })
  assert.strictEqual(r.status, 200)
  assert.strictEqual(rows('affiliate_applications').length, 0)
  r = await applyPost({ ...application, terms_accepted: false })
  assert.strictEqual(r.status, 400)
  r = await applyPost({ ...application, program: 'partner-two' })
  assert.strictEqual(r.status, 404)
  r = await applyPost(application)
  assert.strictEqual(r.status, 201, JSON.stringify(r.body))
  r = await applyPost(application)
  assert.strictEqual(r.status, 409)
  assert.strictEqual(rows('affiliate_applications').length, 1)
  assert.strictEqual(rows('affiliates').length, 1, 'a public application never creates an affiliate')
  assert.ok(rows('affiliate_applications')[0].ip_hash && !rows('affiliate_applications')[0].ip_hash.includes('198.51'))
  ok('honeypot swallowed, validation 400, private program 404, real application 201, duplicate 409, no affiliate minted, IP hashed')
  for (let i = 0; i < 5; i++) await applyPost({ ...application, email: `bulk${i}@creator-b.example.com` }, '198.51.100.99')
  r = await applyPost({ ...application, email: 'bulk9@creator-b.example.com' }, '198.51.100.99')
  assert.strictEqual(r.status, 429)
  ok('the sixth application from one connection in an hour is rate limited')

  r = await adminPost({ action: 'applications.list', status: 'pending' })
  const benApp = r.body.applications.find((a) => a.email === 'ben@creator-b.example.com')
  assert.ok(benApp)
  r = await adminPost({ action: 'applications.approve', id: benApp.id, code: 'BEN20' })
  assert.strictEqual(r.status, 200, JSON.stringify(r.body))
  assert.strictEqual(r.body.code, 'BEN20')
  assert.ok(r.body.join_url)
  const benJoin = tokenFromJoinUrl(r.body.join_url)
  const ben = rows('affiliates').find((a) => a.email === 'ben@creator-b.example.com')
  assert.strictEqual(ben.status, 'active')
  assert.strictEqual(ben.payout_method, 'paypal')
  const mBen1 = rows('affiliate_memberships').find((m) => m.affiliate_id === ben.id && m.program_id === P1.id)
  assert.strictEqual(mBen1.status, 'active')
  r = await adminPost({ action: 'applications.approve', id: benApp.id })
  assert.strictEqual(r.status, 409)
  ok('approved Ben: affiliate + active membership + code BEN20 + join link; approving twice is 409')

  const caraApp = rows('affiliate_applications').find((a) => a.email === 'bulk0@creator-b.example.com')
  r = await adminPost({ action: 'applications.reject', id: caraApp.id, note: 'No relevant audience' })
  assert.strictEqual(r.status, 200)
  assert.strictEqual(rows('affiliate_applications').find((a) => a.id === caraApp.id).status, 'rejected')
  assert.ok(!rows('affiliates').some((a) => a.email === 'bulk0@creator-b.example.com'))
  ok('rejected another applicant: nothing created, note kept')

  r = await call(portal, env.post({ action: 'join_accept', token: benJoin, terms_accepted: true, privacy_accepted: true }))
  assert.strictEqual(r.status, 200)
  const benRow = rows('affiliates').find((a) => a.id === ben.id)
  db.addUser('ben-jwt', { id: benRow.user_id, email: benRow.email })
  ok('Ben set up his login through the join link')

  section('4. one affiliate in two programs, approved per program')
  r = await adminPost({ action: 'affiliates.invite', email: 'ben@creator-b.example.com', full_name: 'Ben Creator', program_slugs: ['partner-two'], code: 'BENP2' })
  assert.strictEqual(r.status, 201)
  const mBen2 = rows('affiliate_memberships').find((m) => m.affiliate_id === ben.id && m.program_id === P2.id)
  assert.strictEqual(mBen2.status, 'invited')
  r = await click('/r/partner-two/BENP2')
  assert.strictEqual(r.headers.Location, 'https://partner-two.example.com/')
  r = await adminPost({ action: 'memberships.approve', id: mBen2.id })
  assert.strictEqual(r.status, 200)
  assert.strictEqual(r.body.membership.status, 'active')
  r = await adminPost({ action: 'memberships.add', affiliate_id: ana.id, program_id: P2.id, code: 'ANAP2' })
  assert.strictEqual(r.status, 201)
  const mAna2 = r.body.membership
  assert.strictEqual(mAna2.referral_link, 'https://app.getbrandgeo.com/r/partner-two/ANAP2')
  assert.strictEqual(rows('affiliates').length, 2)
  ok('Ben was invited to and approved for program 2; Ana was added directly; still two affiliates, four memberships')

  section('5. referral click')
  r = await click('/r/brandgeo/ANA10', { query: { utm_campaign: 'newsletter-sept', utm_content: 'hero' } })
  assert.strictEqual(r.status, 302)
  let loc = new URL(r.headers.Location)
  assert.strictEqual(loc.origin + loc.pathname, 'https://getbrandgeo.com/')
  assert.strictEqual(loc.searchParams.get('ref'), 'ANA10')
  assert.strictEqual(loc.searchParams.get('utm_source'), 'affiliate')
  assert.strictEqual(loc.searchParams.get('utm_medium'), 'referral')
  assert.strictEqual(loc.searchParams.get('utm_campaign'), 'newsletter-sept')
  assert.strictEqual(loc.searchParams.get('utm_content'), 'hero')
  assert.strictEqual(loc.searchParams.get('ref_days'), '30')
  const RID1 = loc.searchParams.get('bg_rid')
  assert.match(RID1, /^[A-Za-z0-9_-]{16,64}$/)
  assert.strictEqual(r.headers['Cache-Control'], 'no-store, private')
  const v1 = rows('affiliate_visits')[0]
  assert.strictEqual(v1.visit_token, RID1)
  assert.strictEqual(v1.membership_id, mAna1.id)
  assert.strictEqual(v1.ua_family, 'windows')
  assert.strictEqual(v1.referrer_host, 'partner-a.example.com')
  assert.deepStrictEqual(v1.utm, { utm_campaign: 'newsletter-sept', utm_content: 'hero' })
  assert.ok(v1.ip_hash && !v1.ip_hash.includes('203.0.113'))
  assert.strictEqual(rows('affiliate_memberships').find((m) => m.id === mAna1.id).clicks_total, 1)
  ok('a valid click 302s with ref, bg_rid, ref_days and the affiliate UTMs, keeps partner UTMs, records one anonymous visit')
  r = await click('/r/brandgeo/ana10')
  assert.strictEqual(new URL(r.headers.Location).searchParams.get('ref'), 'ANA10')
  assert.strictEqual(rows('affiliate_visits').length, 2)
  r = await click('/r/brandgeo/ANA10', { ua: 'facebookexternalhit/1.1' })
  assert.strictEqual(r.status, 302)
  r = await click('/r/brandgeo/ANA10', { method: 'HEAD' })
  assert.strictEqual(r.status, 302)
  assert.strictEqual(rows('affiliate_visits').length, 2)
  r = await click('/r/brandgeo/NOPE')
  assert.strictEqual(r.headers.Location, 'https://getbrandgeo.com/')
  r = await click('/r/no-such-program/ANA10')
  assert.strictEqual(r.headers.Location, 'https://getbrandgeo.com/')
  r = await click('/r/partner-two/ANA10')
  assert.strictEqual(r.headers.Location, 'https://partner-two.example.com/')
  assert.strictEqual(rows('affiliate_visits').length, 2)
  ok('codes are case-insensitive; bots, HEAD, unknown codes and a code used on the wrong program redirect without a visit')
  for (let i = 0; i < 40; i++) await click('/r/brandgeo/ANA10', { ip: '203.0.113.77' })
  assert.strictEqual(rows('affiliate_visits').filter((v) => v.ip_hash === rows('affiliate_visits')[2].ip_hash).length, 30)
  ok('one connection is capped at 30 recorded clicks per minute (the RPC rate limit, emulated by the fake)')

  section('6. lead and sale through the conversion API')
  r = await api(KEY1, { idempotency_key: 'lead:client:501', conversion_type: 'lead', referral_id: RID1, external_id: 'client:501', customer_email: 'Buyer@Customer-X.example.com' })
  assert.strictEqual(r.status, 201, JSON.stringify(r.body))
  assert.strictEqual(r.body.commission, null)
  assert.strictEqual(r.body.conversion.source, 'link')
  assert.strictEqual(r.body.conversion.customer_ref, 'b***@customer-x.example.com')
  const attX = rows('affiliate_attributions').find((a) => a.external_customer_id === `email:${core.hashEmail('buyer@customer-x.example.com')}`)
  assert.ok(attX)
  assert.strictEqual(attX.membership_id, mAna1.id)
  assert.strictEqual(attX.visit_token, RID1)
  assert.strictEqual(attX.source, 'link')
  assert.strictEqual(Date.parse(attX.expires_at) - Date.parse(v1.created_at), 30 * 86400000)
  ok('a lead with the referral id attributes the hashed email to Ana for 30 days and earns nothing on its own')

  r = await api(KEY1, { idempotency_key: 'order_1001', conversion_type: 'sale', external_id: 'order_1001', customer_email: 'buyer@customer-x.example.com', amount: '299.00', currency: 'eur' })
  assert.strictEqual(r.status, 201, JSON.stringify(r.body))
  assert.strictEqual(r.body.commission.amount_cents, 5980)
  assert.strictEqual(r.body.commission.amount, '59.80')
  assert.strictEqual(r.body.commission.status, 'pending')
  assert.strictEqual(r.body.conversion.currency, 'EUR')
  const sale1 = rows('affiliate_conversions').find((c) => c.idempotency_key === 'order_1001')
  assert.strictEqual(sale1.membership_id, mAna1.id)
  const comm1 = rows('affiliate_commissions').find((c) => c.conversion_id === sale1.id)
  assert.strictEqual(Date.parse(comm1.approve_after) - Date.parse(sale1.occurred_at), 30 * 86400000)
  assert.deepStrictEqual(comm1.rule_snapshot.rule, 'percent_of_sale')
  const attX2 = rows('affiliate_attributions').find((a) => a.id === attX.id)
  assert.strictEqual(attX2.converted_at, sale1.occurred_at)
  assert.ok(attX2.recurring_until)
  ok('a sale with only the customer email finds the stored attribution: 20% of 299.00 = 59.80, pending until day 30, attribution locked')

  r = await api(KEY1, { idempotency_key: 'order_1001', conversion_type: 'sale', amount: '999.00', customer_email: 'buyer@customer-x.example.com' })
  assert.strictEqual(r.status, 200)
  assert.strictEqual(r.body.duplicate, true)
  assert.strictEqual(r.body.conversion.id, sale1.id)
  assert.strictEqual(r.body.commission.id, comm1.id)
  r = await api(KEY1, { idempotency_key: 'order_1001_retry', conversion_type: 'sale', external_id: 'order_1001', amount: '299.00', customer_email: 'buyer@customer-x.example.com' })
  assert.strictEqual(r.status, 200)
  assert.strictEqual(r.body.duplicate, true)
  assert.strictEqual(rows('affiliate_conversions').filter((c) => c.external_id === 'order_1001').length, 1)
  assert.strictEqual(rows('affiliate_commissions').length, 1)
  ok('the same idempotency key, or the same order id under a new key, returns the original and writes nothing')

  r = await api(KEY1, { idempotency_key: 'order_1002', conversion_type: 'sale', external_id: 'order_1002', amount_cents: 10000, customer_email: 'buyer@customer-x.example.com', commission: '999.00', commission_cents: 99900 })
  assert.strictEqual(r.status, 201)
  assert.strictEqual(r.body.commission.amount_cents, 2000)
  ok('a commission sent by the client is ignored; the server computes 20% of 100.00')

  section('7. cross-program isolation')
  r = await api(KEY2, { idempotency_key: 'p2-a', conversion_type: 'sale', referral_id: RID1, amount: '10.00' })
  assert.strictEqual(r.status, 422)
  r = await api(KEY2, { idempotency_key: 'p2-b', conversion_type: 'sale', affiliate_code: 'ANA10', amount: '10.00' })
  assert.strictEqual(r.status, 422)
  r = await api(KEY2, { idempotency_key: 'p2-c', conversion_type: 'sale', customer_email: 'buyer@customer-x.example.com', amount: '10.00' })
  assert.strictEqual(r.status, 422)
  r = await api(KEY2, { idempotency_key: 'order_1001', conversion_type: 'sale', amount: '10.00', affiliate_code: 'ANAP2' })
  assert.strictEqual(r.status, 200, 'idempotency keys are global; the caller gets the existing record and nothing is written')
  assert.strictEqual(r.body.duplicate, true)
  assert.strictEqual(rows('affiliate_conversions').filter((c) => c.program_id === P2.id).length, 0)
  ok("program 2's key cannot use program 1's referral id, code or customer attribution")

  r = await api(KEY2, { idempotency_key: 'p2-lead-1', conversion_type: 'qualified_lead', affiliate_code: 'ANAP2', external_customer_id: 'p2-customer-1', customer_ref: 'Company One' })
  assert.strictEqual(r.status, 201, JSON.stringify(r.body))
  assert.strictEqual(r.body.commission.amount_cents, 10000)
  assert.strictEqual(rows('affiliate_commissions').find((c) => c.id === r.body.commission.id).approve_after <= new Date().toISOString(), true, 'approval_days 0 means approvable now')
  ok('program 2 pays its own fixed EUR 100 per qualified lead, keyed on the partner project customer id')

  section('8. coupon override and last touch vs first touch')
  r = await adminPost({ action: 'codes.create', membership_id: mBen1.id, code: 'bensave', kind: 'coupon', stripe_promotion_code_id: 'promo_ben' })
  assert.strictEqual(r.status, 201)
  assert.strictEqual(r.body.code.code, 'BENSAVE')
  r = await adminPost({ action: 'codes.create', membership_id: mAna1.id, code: 'BENSAVE', kind: 'coupon' })
  assert.strictEqual(r.status, 409)
  ok('coupon code BENSAVE issued to Ben; the same code cannot exist twice in a program')
  r = await click('/r/brandgeo/ANA10', { ip: '203.0.113.9' })
  const RID2 = new URL(r.headers.Location).searchParams.get('bg_rid')
  r = await api(KEY1, { idempotency_key: 'lead:y', conversion_type: 'lead', referral_id: RID2, customer_email: 'shopper@customer-y.example.com' })
  assert.strictEqual(r.status, 201)
  const attY = () => rows('affiliate_attributions').find((a) => a.external_customer_id === `email:${core.hashEmail('shopper@customer-y.example.com')}`)
  assert.strictEqual(attY().membership_id, mAna1.id)
  r = await api(KEY1, { idempotency_key: 'order_y1', conversion_type: 'sale', affiliate_code: 'BENSAVE', customer_email: 'shopper@customer-y.example.com', amount: '100.00' })
  assert.strictEqual(r.status, 201, JSON.stringify(r.body))
  assert.strictEqual(r.body.conversion.source, 'coupon')
  assert.ok(r.body.conversion.flags.includes('duplicate_customer'))
  assert.strictEqual(attY().membership_id, mBen1.id)
  assert.strictEqual(rows('affiliate_commissions').find((c) => c.id === r.body.commission.id).affiliate_id, ben.id)
  assert.ok(rows('affiliate_audit_log').some((a) => a.action === 'attribution.reassigned'))
  ok("a coupon at checkout overrides Ana's earlier link: the sale and commission go to Ben, the switch is flagged and audited")
  r = await click('/r/brandgeo/ANA10', { ip: '203.0.113.9' })
  r = await api(KEY1, { idempotency_key: 'lead:y2', conversion_type: 'lead', referral_id: new URL(r.headers.Location).searchParams.get('bg_rid'), customer_email: 'shopper@customer-y.example.com' })
  assert.strictEqual(attY().membership_id, mBen1.id)
  ok('a later link click cannot take a converted customer back')

  r = await click('/r/brandgeo/ANA10', { ip: '203.0.113.10' })
  const ridZa = new URL(r.headers.Location).searchParams.get('bg_rid')
  r = await click('/r/brandgeo/BEN20', { ip: '203.0.113.10' })
  const ridZb = new URL(r.headers.Location).searchParams.get('bg_rid')
  await api(KEY1, { idempotency_key: 'lead:z1', conversion_type: 'lead', referral_id: ridZa, customer_email: 'z@customer-z.example.com' })
  await api(KEY1, { idempotency_key: 'lead:z2', conversion_type: 'lead', referral_id: ridZb, customer_email: 'z@customer-z.example.com' })
  r = await api(KEY1, { idempotency_key: 'order_z', conversion_type: 'sale', customer_email: 'z@customer-z.example.com', amount: '50.00' })
  assert.strictEqual(rows('affiliate_commissions').find((c) => c.id === r.body.commission.id).affiliate_id, ben.id)
  ok('last touch (program 1 default): the second link wins the sale')

  r = await adminPost({ action: 'programs.update', id: P2.id, patch: { attribution_mode: 'first_touch' } })
  assert.strictEqual(r.status, 200)
  r = await click('/r/partner-two/ANAP2', { ip: '203.0.113.11' })
  const ridWa = new URL(r.headers.Location).searchParams.get('bg_rid')
  r = await click('/r/partner-two/BENP2', { ip: '203.0.113.11' })
  const ridWb = new URL(r.headers.Location).searchParams.get('bg_rid')
  await api(KEY2, { idempotency_key: 'w1', conversion_type: 'lead', referral_id: ridWa, external_customer_id: 'w' })
  await api(KEY2, { idempotency_key: 'w2', conversion_type: 'lead', referral_id: ridWb, external_customer_id: 'w' })
  r = await api(KEY2, { idempotency_key: 'order_w', conversion_type: 'sale', external_customer_id: 'w', amount: '1200.00' })
  assert.strictEqual(r.body.commission.amount_cents, 50000)
  assert.strictEqual(rows('affiliate_commissions').find((c) => c.id === r.body.commission.id).affiliate_id, ana.id)
  ok('first touch (program 2): the first link keeps the sale, fixed EUR 500 per sale')

  section('9. refund reversal and recurring')
  r = await api(KEY1, { action: 'reverse', idempotency_key: 'order_1001', status: 'refunded', reason: 'chargeback' })
  assert.strictEqual(r.status, 200, JSON.stringify(r.body))
  assert.strictEqual(r.body.conversion.status, 'refunded')
  assert.strictEqual(r.body.commissions[0].status, 'reversed')
  assert.strictEqual(rows('affiliate_commissions').find((c) => c.id === comm1.id).status, 'reversed')
  r = await api(KEY1, { action: 'reverse', idempotency_key: 'order_1001', status: 'refunded' })
  assert.strictEqual(r.status, 200)
  assert.deepStrictEqual(r.body.commissions, [])
  r = await api(KEY2, { action: 'reverse', idempotency_key: 'order_1001', status: 'refunded' })
  assert.strictEqual(r.status, 404)
  ok("a refund through the API reverses the unpaid commission; repeating is harmless; another program's key cannot reverse it")
  const sale2 = rows('affiliate_conversions').find((c) => c.idempotency_key === 'order_1002')
  r = await adminPost({ action: 'conversions.reverse', id: sale2.id })
  assert.strictEqual(r.status, 400)
  r = await adminPost({ action: 'conversions.reverse', id: sale2.id, status: 'cancelled', reason: 'Customer cancelled within 14 days' })
  assert.strictEqual(r.status, 200)
  assert.strictEqual(rows('affiliate_commissions').find((c) => c.conversion_id === sale2.id).status, 'reversed')
  ok('an admin reversal needs a reason and reverses the commission the same way')
  r = await api(KEY1, { idempotency_key: 'order_1003', conversion_type: 'sale', amount: '10.00', customer_email: 'buyer@customer-x.example.com', status: 'refunded' })
  assert.strictEqual(r.status, 201)
  assert.strictEqual(r.body.conversion.status, 'refunded')
  assert.strictEqual(r.body.commission, null)
  ok('a conversion that arrives already refunded is recorded reversed with no commission')

  r = await click('/r/brandgeo/ANA10', { ip: '203.0.113.12' })
  const ridR = new URL(r.headers.Location).searchParams.get('bg_rid')
  r = await api(KEY1, { idempotency_key: 'order_2001', conversion_type: 'sale', referral_id: ridR, external_customer_id: 'customer_88', amount: '299.00', occurred_at: '2026-09-12T12:00:00Z' })
  assert.strictEqual(r.status, 201, JSON.stringify(r.body))
  const sale3 = r.body.conversion
  const commA = rows('affiliate_commissions').find((c) => c.conversion_id === sale3.id)
  assert.strictEqual(commA.amount_cents, 5980)
  r = await api(KEY1, { idempotency_key: 'renewal_2001_m2', conversion_type: 'recurring', external_customer_id: 'customer_88', amount: '299.00', occurred_at: '2026-10-12T12:00:00Z' })
  assert.strictEqual(r.status, 201, JSON.stringify(r.body))
  assert.strictEqual(r.body.commission.amount_cents, 5980)
  assert.strictEqual(rows('affiliate_conversions').find((c) => c.idempotency_key === 'renewal_2001_m2').parent_conversion_id, sale3.id)
  const commB = rows('affiliate_commissions').find((c) => c.id === r.body.commission.id)
  r = await api(KEY1, { idempotency_key: 'renewal_2001_m14', conversion_type: 'recurring', external_customer_id: 'customer_88', amount: '299.00', occurred_at: '2027-11-12T12:00:00Z' })
  assert.strictEqual(r.status, 201)
  assert.strictEqual(r.body.commission, null)
  assert.strictEqual(rows('affiliate_conversions').find((c) => c.idempotency_key === 'renewal_2001_m14').metadata.no_commission_reason, 'recurring_window_ended')
  ok('a renewal in month 2 earns 20% again, linked to the sale; month 14 is outside the 12-month window')

  section('10. approval, payout batch, mark paid')
  r = await adminPost({ action: 'commissions.approve', ids: [commA.id, commB.id, comm1.id] })
  assert.strictEqual(r.status, 200)
  assert.deepStrictEqual(r.body.updated.map((u) => u.status), ['approved', 'approved'])
  assert.deepStrictEqual(r.body.skipped, [{ id: comm1.id, from: 'reversed' }])
  ok('approved the two live commissions by hand; the reversed one is skipped, not resurrected')
  clock = new Date('2026-11-01T00:00:00Z')
  r = await adminPost({ action: 'commissions.mature' })
  assert.ok(r.body.matured >= 1)
  const pendingLeft = rows('affiliate_commissions').filter((c) => c.status === 'pending')
  assert.strictEqual(pendingLeft.length, 0)
  ok('after the approval delay the maturation job approves what is left pending (the RPC, emulated by the fake)')

  r = await adminPost({ action: 'payouts.candidates' })
  const candAna = r.body.candidates.find((c) => c.affiliate_id === ana.id && c.currency === 'EUR')
  assert.strictEqual(candAna.total_cents, 5980 + 5980 + 10000 + 50000)
  assert.strictEqual(candAna.meets_threshold, true)
  assert.strictEqual(candAna.min_payout_cents, 10000, 'the strictest program threshold applies')
  assert.strictEqual(candAna.has_payout_details, true)
  ok('payable candidates are grouped per affiliate and currency against the highest program threshold')

  r = await adminPost({ action: 'payouts.create_batch', affiliate_id: ana.id, currency: 'EUR', commission_ids: [commA.id, commB.id, comm1.id], note: 'September' })
  assert.strictEqual(r.status, 201, JSON.stringify(r.body))
  const batch = r.body.batch
  assert.strictEqual(batch.status, 'draft')
  assert.strictEqual(batch.total_cents, 11960)
  assert.strictEqual(batch.item_count, 2)
  assert.strictEqual(batch.payout_method, 'wise')
  assert.deepStrictEqual(Object.keys(batch.payout_details).sort(), ['account_holder', 'email', 'iban'])
  for (const id of [commA.id, commB.id]) {
    const c = rows('affiliate_commissions').find((x) => x.id === id)
    assert.strictEqual(c.status, 'payable')
    assert.ok(c.payout_item_id)
  }
  assert.strictEqual(rows('affiliate_commissions').find((x) => x.id === comm1.id).status, 'reversed')
  ok('a draft batch snapshots the payout details and moves only the approved rows to payable')

  r = await adminPost({ action: 'export', kind: 'commissions', affiliate_id: ana.id })
  assert.strictEqual(r.status, 200)
  assert.strictEqual(r.headers['Content-Type'], 'text/csv; charset=utf-8')
  assert.match(r.headers['Content-Disposition'], /^attachment; filename="affiliate-commissions-\d{4}-\d{2}-\d{2}\.csv"$/)
  assert.ok(r.body.endsWith('\r\n'), 'CSV ends with a line terminator')
  const lines = r.body.replace(/\r\n$/, '').split('\r\n')
  assert.strictEqual(lines[0], core.EXPORT_COLUMNS.commissions.join(','))
  assert.strictEqual(lines.length - 1, rows('affiliate_commissions').filter((c) => c.affiliate_id === ana.id).length)
  assert.ok(lines[1].includes(ana.email))
  r = await adminPost({ action: 'export', kind: 'payout_items', affiliate_id: ana.id })
  assert.strictEqual(r.body.split('\r\n')[0], core.EXPORT_COLUMNS.payout_items.join(','))
  r = await adminPost({ action: 'export', kind: 'nope' })
  assert.strictEqual(r.status, 400)
  ok('CSV exports carry the stable column set and honour the filters')

  r = await adminPost({ action: 'payouts.mark_paid', id: batch.id })
  assert.strictEqual(r.status, 400)
  r = await adminPost({ action: 'payouts.mark_paid', id: batch.id, external_reference: 'WISE-TX-98765', paid_at: '2026-11-05T09:00:00Z' })
  assert.strictEqual(r.status, 200, JSON.stringify(r.body))
  assert.strictEqual(r.body.batch.status, 'paid')
  assert.strictEqual(r.body.batch.external_reference, 'WISE-TX-98765')
  for (const id of [commA.id, commB.id]) {
    const c = rows('affiliate_commissions').find((x) => x.id === id)
    assert.strictEqual(c.status, 'paid')
    assert.strictEqual(c.paid_at, '2026-11-05T09:00:00.000Z')
  }
  assert.ok(rows('affiliate_audit_log').some((a) => a.action === 'payout.batch_paid' && a.after.external_reference === 'WISE-TX-98765' && a.actor_id === 'admin-1'))
  r = await adminPost({ action: 'payouts.mark_paid', id: batch.id, external_reference: 'again' })
  assert.strictEqual(r.status, 409)
  ok('mark paid needs the external reference, stamps date and reference on every row, audits with the admin id, and cannot run twice')

  r = await api(KEY1, { action: 'reverse', idempotency_key: 'order_2001', status: 'refunded', reason: 'refund after payout' })
  assert.strictEqual(r.status, 200)
  const paidComm = rows('affiliate_commissions').find((x) => x.id === commA.id)
  assert.strictEqual(paidComm.status, 'paid')
  assert.strictEqual(paidComm.reconciliation_flag, true)
  assert.match(paidComm.reconciliation_note, /clawback/)
  ok('a refund after payout never changes the paid row: it is flagged for reconciliation')

  const benApproved = rows('affiliate_commissions').filter((c) => c.affiliate_id === ben.id && c.status === 'approved')
  r = await adminPost({ action: 'payouts.create_batch', affiliate_id: ben.id, currency: 'EUR', commission_ids: benApproved.map((c) => c.id) })
  const benBatch = r.body.batch
  r = await adminPost({ action: 'payouts.cancel', id: benBatch.id, note: 'wrong month' })
  assert.strictEqual(r.body.batch.status, 'cancelled')
  for (const c of benApproved) assert.strictEqual(rows('affiliate_commissions').find((x) => x.id === c.id).status, 'approved')
  ok('cancelling a draft batch returns its rows to approved')

  section('11. the affiliate portal')
  r = await call(portal, env.post({ action: 'me' }, { token: 'ana-jwt' }))
  assert.strictEqual(r.status, 200)
  const m1 = r.body.memberships.find((m) => m.program.slug === 'brandgeo')
  assert.strictEqual(m1.referral_link, 'https://app.getbrandgeo.com/r/brandgeo/ANA10')
  assert.ok(m1.clicks_total >= 5)
  assert.strictEqual(r.body.memberships.find((m) => m.program.slug === 'partner-two').referral_code, 'ANAP2')
  assert.strictEqual(r.body.commissions.length, rows('affiliate_commissions').filter((c) => c.affiliate_id === ana.id).length)
  assert.strictEqual(r.body.payouts[0].external_reference, 'WISE-TX-98765')
  assert.strictEqual(r.body.stats.by_currency.EUR.paid, '119.60')
  const meRaw = JSON.stringify(r.body)
  for (const forbidden of ['customer_email', 'external_customer_id', 'idempotency_key', 'ip_hash', ben.email, 'BENSAVE', 'BEN20']) assert.ok(!meRaw.includes(forbidden), `portal leaks ${forbidden}`)
  assert.ok(r.body.conversions.every((c) => /^(b\*\*\*@|customer|Company|z\*\*\*@|s\*\*\*@)/.test(c.customer_ref)))
  ok("Ana's dashboard: her links, clicks, commissions and the paid batch, customers masked, nothing of Ben's")
  r = await call(portal, env.post({ action: 'upload_url', batch_id: batch.id, filename: 'invoice sept.pdf' }, { token: 'ana-jwt' }))
  assert.strictEqual(r.status, 200)
  assert.ok(r.body.path.startsWith(`${ana.id}/${batch.id}/`))
  r = await call(portal, env.post({ action: 'attach_document', batch_id: batch.id, path: r.body.path, name: 'invoice sept.pdf', size: 1234 }, { token: 'ana-jwt' }))
  assert.strictEqual(r.status, 200)
  assert.strictEqual(r.body.documents[0].uploaded_by, 'affiliate')
  r = await call(portal, env.post({ action: 'upload_url', batch_id: batch.id, filename: 'x.exe' }, { token: 'ana-jwt' }))
  assert.strictEqual(r.status, 400)
  r = await call(portal, env.post({ action: 'upload_url', batch_id: batch.id, filename: 'x.pdf' }, { token: 'ben-jwt' }))
  assert.strictEqual(r.status, 404)
  ok('Ana attaches an invoice to her own payout; executables and other affiliates are refused')
  r = await call(portal, env.post({ action: 'update_payout', payout_method: 'paypal', payout_details: { email: 'ana-pay@partner-a.example.com', card_number: '4111', password: 'x' } }, { token: 'ana-jwt' }))
  assert.deepStrictEqual(r.body.payout_details, { email: 'ana-pay@partner-a.example.com' })
  r = await call(portal, env.post({ action: 'apply_program', program: 'brandgeo' }, { token: 'ana-jwt' }))
  assert.strictEqual(r.status, 409)
  r = await call(portal, env.post({ action: 'apply_program', program: 'partner-two' }, { token: 'ben-jwt' }))
  assert.strictEqual(r.status, 404, 'private programs cannot be applied to from the portal either')
  ok('payout details are sanitised on update; duplicate and private applications are refused')

  section('12. admin overview, audit trail, no hard deletes')
  r = await adminPost({ action: 'overview' })
  assert.strictEqual(r.body.counts.affiliates_active, 2)
  assert.strictEqual(r.body.counts.applications_pending, 4)
  assert.strictEqual(r.body.counts.reconciliation_flags, 1)
  assert.strictEqual(r.body.totals.EUR.paid, '119.60')
  ok('the overview totals match the ledger')
  r = await adminPost({ action: 'audit.list', entity_type: 'payout_batch' })
  assert.ok(r.body.entries.some((e) => e.action === 'payout.batch_paid'))
  r = await adminPost({ action: 'conversions.list', program_id: P1.id, conversion_type: 'sale' })
  assert.ok(r.body.conversions.every((c) => c.conversion_type === 'sale' && c.program_id === P1.id))
  assert.ok(r.body.conversions.every((c) => c.affiliate_email))
  r = await adminPost({ action: 'visits.list', program_id: P2.id })
  assert.ok(r.body.visits.length >= 2 && r.body.visits.every((v) => v.program_id === P2.id))
  ok('list actions filter by program and type and decorate rows with affiliate names')
  const deletes = db.calls.filter((c) => c.op === 'delete')
  assert.ok(deletes.every((c) => c.table === 'affiliate_payout_items'), `unexpected delete on ${JSON.stringify(deletes)}`)
  assert.ok(rows('affiliate_conversions').length >= 12)
  assert.ok(rows('affiliate_attributions').length >= 5)
  ok('the only delete anywhere is a payout item leaving a draft batch; conversions, commissions, attributions and batches are never removed')

  console.log(`\n${passed} checks passed`)
}

main().catch((e) => { console.error(e); process.exit(1) })
